<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/1_24_Pandas Inspection.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [ ]:

import pandas as pd

df = pd.read_csv('/content/data_jobs.csv', on_bad_lines='skip')

df

<ipython-input-4-179e27bdc483>:3: DtypeWarning: Columns (5,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/data_jobs.csv', on_bad_lines='skip')

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398079,Business Analyst,International Business Analytics Lead,"Amsterdam, Netherlands",via Vacatures Trabajo.org,Full-time,False,Netherlands,2023-04-09 18:54:24,False,False,Netherlands,NaN,NaN,NaN,Rhythm Pharmaceuticals,"['snowflake', 'powerpoint', 'word', 'excel']","{'analyst_tools': ['powerpoint', 'word', 'exce..."
398080,Software Engineer,Performance Analyst,"Larnaca, Cyprus",via LinkedIn Cyprus,Full-time,False,Cyprus,2023-11-06 19:21:48,False,False,Cyprus,NaN,NaN,NaN,HF Markets,['excel'],{'analyst_tools': ['excel']}
398081,Data Analyst,Data Analyst,"Unterschleißheim, Germany",via LinkedIn,Full-time,False,Germany,2023-03-01 18:24:10,False,False,Germany,NaN,NaN,NaN,MZV Moderner Zeitschriften Vertrieb,['power bi'],{'analyst_tools': ['power bi']}
398082,Machine Learning Engineer,ML/DL Engineer (Recommendation systems),India,via LinkedIn,Full-time,False,India,2023-09-07 18:11:04,False,False,India,NaN,NaN,NaN,Akaike Technologies,"['python', 'aws', 'databricks', 'tensorflow', ...","{'cloud': ['aws', 'databricks'], 'libraries': ..."
398083,Data Scientist,Sta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

---

## 🟩 Access Third Row (1.24.1)

In [ ]:
df.iloc[2]

job_title_short                                              Data Engineer
job_title                Data Engineer/Scientist/Analyst, Mid or Senior...
job_location                                               Berlin, Germany
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                    Germany
job_posted_date                                        2023-10-10 13:14:55
job_no_degree_mention                                                False
job_health_insurance                                                 False
job_country                                                        Germany
salary_rate                                                            NaN
salary_year_avg                                                        NaN
salary_hour_avg                                                        NaN
company_name                                      ALPHA Augmented Services
job_skills               ['python', 'sql', 'c#', 'azure', 'airflow', 'd...
job_type_skills          {'analyst_tools': ['dax'], 'cloud': ['azure'],...
Name: 2, dtype: object

---

## 🟨 Unique Job Countries (1.24.2)

In [ ]:
df['job_country'].unique()

array(['United States', 'Mexico', 'Germany', 'Sudan', 'Romania',
       'Denmark', 'Switzerland', 'France', 'Brazil', 'United Kingdom',
       'India', 'Poland', 'Belgium', 'Russia', 'Serbia', 'Singapore',
       'Costa Rica', 'Ireland', 'Italy', 'Malaysia', 'Canada', 'Uruguay',
       'Namibia', 'Estonia', 'Israel', 'Hungary', 'Austria',
       'Philippines', 'Egypt', 'Australia', 'Chile', 'Spain',
       'Netherlands', 'South Africa', 'Colombia', 'Hong Kong', 'Kuwait',
       'Finland', 'Luxembourg', 'China', 'Puerto Rico', 'Sweden',
       'Saudi Arabia', 'Argentina', 'Turkey', 'Panama', 'Nigeria',
       'New Zealand', 'Ukraine', 'Jordan', 'United Arab Emirates',
       'Armenia', 'Pakistan', 'Lesotho', 'Mauritius', 'Portugal',
       'Bahrain', 'Taiwan', "Côte d'Ivoire", 'U.S. Virgin Islands',
       'Réunion', 'Kazakhstan', 'Lithuania', 'Moldova', 'Belarus',
       'Cyprus', 'Bulgaria', 'Honduras', 'Czechia', 'Peru', 'South Korea',
       'Malta', 'Indonesia', 'Tunisia', 'Latvia', 'Slovakia', 'Lebanon',
       'Japan', 'Sri Lanka', 'Slovenia', 'Bangladesh', 'Greece',
       'Ecuador', 'Oman', 'Kenya', 'Guyana', 'Vietnam', 'Norway',
       'Senegal', 'El Salvador', 'Iceland', 'Thailand', 'Ghana',
       'Croatia', 'Myanmar', 'Nepal', 'Morocco', 'Guadeloupe', 'Iraq',
       'Palestine', 'Guinea', 'Albania', 'Guatemala', 'Qatar', 'Uganda',
       'Bolivia', nan, 'Dominican Republic', 'Ethiopia', 'Haiti',
       'Uzbekistan', 'Bahamas', 'Liberia', 'Montenegro', 'Cayman Islands',
       'Mongolia', 'Macedonia (FYROM)', 'Azerbaijan', 'Burkina Faso',
       'Guam', 'Trinidad and Tobago', 'Benin', 'Kyrgyzstan',
       'Bosnia and Herzegovina', 'Zambia', 'Cameroon', 'Venezuela',
       'Barbados', 'Togo', 'Rwanda', 'Cambodia', 'Algeria', 'Afghanistan',
       'Congo, Democratic Republic of the', 'Zimbabwe', 'Jamaica',
       'Suriname', 'Mozambique', 'Yemen', 'Tanzania', 'Madagascar',
       'Mali', 'Paraguay', 'Brunei', 'Malawi', 'Nicaragua', 'Libya',
       'Tajikistan', 'Mauritania', 'Botswana', 'Fiji',
       'Northern Mariana Islands', 'Angola', 'Somalia',
       'Papua New Guinea', 'Gambia', 'Djibouti', 'Laos', 'Curaçao',
       'Maldives'], dtype=object)

---

## 🟨 Filter by Job Schedule Type and Display (1.24.3)

In [ ]:
filtered_df = df[df['job_schedule_type'] == 'Full-time']
filtered_df.head(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."

---

## 🟥 Check Missing Values (1.24.4)

In [ ]:
not_na_values = df[df['job_skills'].notna()]
not_na_values

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398078,Data Engineer,Data Engineer,"Toronto, ON, Canada",via LinkedIn,Full-time,False,Canada,2023-12-12 18:28:54,True,False,Canada,NaN,NaN,NaN,Elevate Security,"['python', 'aws', 'spark', 'airflow', 'kuberne...","{'cloud': ['aws'], 'libraries': ['spark', 'air..."
398079,Business Analyst,International Business Analytics Lead,"Amsterdam, Netherlands",via Vacatures Trabajo.org,Full-time,False,Netherlands,2023-04-09 18:54:24,False,False,Netherlands,NaN,NaN,NaN,Rhythm Pharmaceuticals,"['snowflake', 'powerpoint', 'word', 'excel']","{'analyst_tools': ['powerpoint', 'word', 'exce..."
398080,Software Engineer,Performance Analyst,"Larnaca, Cyprus",via LinkedIn Cyprus,Full-time,False,Cyprus,2023-11-06 19:21:48,False,False,Cyprus,NaN,NaN,NaN,HF Markets,['excel'],{'analyst_tools': ['excel']}
398081,Data Analyst,Data Analyst,"Unterschleißheim, Germany",via LinkedIn,Full-time,False,Germany,2023-03-01 18:24:10,False,False,Germany,NaN,NaN,NaN,MZV Moderner Zeitschriften Vertrieb,['power bi'],{'analyst_tools': ['power bi']}
398082,Machine Learning Engineer,ML/DL Engineer (Recommendation systems),India,via LinkedIn,Full-time,False,India,2023-09-07 18:11:04,False,False,India,NaN,NaN,NaN,Akaike Technologies,"['python', 'aws', 'databricks', 'tensorflow', ...","{'cloud': ['aws', 'databricks'], 'libraries': ..."

---