<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/Blank Python Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank Python Notebook
A blank Colab notebook to work practice problems from my ["Python for Data Analytics Course"](https://www.youtube.com/watch?v=wUSDVGivd-8).

In [ ]:
import pandas as pd

df = pd.read_csv("hf://datasets/lukebarousse/data_jobs/data_jobs.csv")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [ ]:
df['job_country'].isin(['Greece']).any()

np.True_

In [ ]:
 gr_jobs = df[df['job_country'] == 'Greece']
 gr_jobs

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
1003,Data Analyst,Data Quality Analyst – Greece,Greece,via LinkedIn,Full-time,False,Greece,2023-02-24 13:56:02,False,False,Greece,NaN,NaN,NaN,Poudouleveis.gr,['sql'],{'programming': ['sql']}
1050,Data Engineer,"Sr. Manager, Regulatory Quality Assurance Data...","Thessaloniki, Greece",via LinkedIn,Full-time,False,Greece,2023-02-24 13:56:18,False,False,Greece,NaN,NaN,NaN,Poudouleveis.gr,"['oracle', 'sharepoint']","{'analyst_tools': ['sharepoint'], 'cloud': ['o..."
1235,Data Analyst,Data Analyst,"Thessaloniki, Greece",via LinkedIn,Full-time,False,Greece,2023-11-24 13:29:51,False,False,Greece,NaN,NaN,NaN,Campeón Gaming,"['sql', 'python', 'r', 'tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi'], 'pr..."
1281,Data Engineer,(Mid/ Senior) Data Engineer,"Athens, Greece",via LinkedIn,Full-time,False,Greece,2023-03-21 13:40:13,False,False,Greece,NaN,NaN,NaN,Dialectica,"['sql', 'python', 'aws', 'flow']","{'cloud': ['aws'], 'other': ['flow'], 'program..."
1831,Data Scientist,"Senior Associate, Data Science","Thessaloniki, Greece",via LinkedIn,Full-time,False,Greece,2023-02-24 13:56:06,False,False,Greece,NaN,NaN,NaN,Poudouleveis.gr,"['r', 'python', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
776435,Data Analyst,Data Architect,"Athens, Greece",via Startup Jobs,Full-time,False,Greece,2023-01-15 01:26:12,False,False,Greece,NaN,NaN,NaN,Uni Systems,['express'],{'webframeworks': ['express']}
778433,Business Analyst,Sales Analyst,Greece,via BeBee,Full-time,False,Greece,2023-08-15 05:17:56,False,False,Greece,NaN,NaN,NaN,Randstad Hellas,['excel'],{'analyst_tools': ['excel']}
780458,Data Engineer,Azure Cloud Data Engineer,"Athens, Greece",via Indeed,Full-time,False,Greece,2023-01-05 05:56:33,False,False,Greece,NaN,NaN,NaN,Netcompany-Intrasoft,"['sql', 'c#', 'powershell', 'python', 'azure',...","{'analyst_tools': ['power bi', 'tableau', 'dax..."
780973,Data Engineer,Data Engineer,"Athens, Greece",via Jooble,Full-time,False,Greece,2023-01-05 06:56:33,False,False,Greece,NaN,NaN,NaN,improvIT,"['sql', 'python', 'java', 'c#', 'nosql', 'mong...","{'analyst_tools': ['sap', 'ssis', 'tableau', '..."
783226,Software Engineer,Senior Software Engineer - Query Languages,Anywhere,via LinkedIn,Full-time,True,Greece,2023-01-10 06:34:00,False,False,Greece,NaN,NaN,NaN,Elastic,"['java', 'mongodb', 'mongodb', 'elasticsearch'...","{'databases': ['mongodb', 'elasticsearch', 'po..."

In [ ]:
gr_jobs = gr_jobs[gr_jobs['salary_year_avg'].notna()]

gr_jobs

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
11741,Data Scientist,Junior Data Scientist,"Athens, Greece",via Ai-Jobs.net,Full-time,False,Greece,2023-01-16 14:07:22,False,False,Greece,year,64821.5,NaN,PeopleCert,"['python', 'azure', 'databricks', 'spark', 'po...","{'analyst_tools': ['power bi'], 'cloud': ['azu..."
15254,Senior Data Scientist,Senior Research Engineer,"Nea Smyrni, Greece",via Ai-Jobs.net,Full-time,False,Greece,2023-03-06 14:28:55,False,False,Greece,year,200000.0,NaN,WINGS-ICT-SOLUTIONS,"['word', 'excel', 'powerpoint']","{'analyst_tools': ['word', 'excel', 'powerpoin..."
29149,Software Engineer,Senior Software Engineer (On Image Processing ...,"Paiania, Greece",via Ai-Jobs.net,Full-time,False,Greece,2023-06-29 14:02:41,False,False,Greece,year,89100.0,NaN,INTRALOT,"['go', 'tensorflow', 'linux']","{'libraries': ['tensorflow'], 'os': ['linux'],..."
58901,Data Analyst,Business Intelligence Engineer,"Athens, Greece",via Ai-Jobs.net,Full-time,False,Greece,2023-04-10 06:27:35,False,False,Greece,year,89100.0,NaN,Kaizen Gaming,"['python', 'sql', 'databricks', 'spark', 'tabl...","{'analyst_tools': ['tableau'], 'cloud': ['data..."
80165,Data Scientist,Lead Data Scientist,"Athens, Greece",via Ai-Jobs.net,Full-time,False,Greece,2023-02-10 00:59:07,False,False,Greece,year,51068.0,NaN,iTechScope,"['python', 'spark', 'kafka', 'kubernetes', 'do...","{'libraries': ['spark', 'kafka'], 'other': ['k..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749852,Data Analyst,Data Architect,"Athens, Greece",via Ai-Jobs.net,Full-time,False,Greece,2023-01-16 21:07:22,False,False,Greece,year,163782.0,NaN,Uni Systems,['express'],{'webframeworks': ['express']}
752893,Data Engineer,Big Data Engineer,"Nea Smyrni, Greece",via Ai-Jobs.net,Full-time,False,Greece,2023-01-19 21:14:22,False,False,Greece,year,45000.0,NaN,INCELLIGENT,"['python', 'java', 'scala', 'sql', 'postgresql...","{'cloud': ['oracle', 'azure', 'aws'], 'databas..."
765797,Machine Learning Engineer,Machine Learning Engineer (Electricity Trading...,"Athens, Greece",via Ai-Jobs.net,Full-time,False,Greece,2023-04-05 01:50:57,False,False,Greece,year,104668.0,NaN,ManpowerGroup Greece,['python'],{'programming': ['python']}
767505,Machine Learning Engineer,AI Engineer,"Athens, Greece",via Ai-Jobs.net,Full-time,False,Greece,2023-07-22 01:43:30,False,False,Greece,year,89100.0,NaN,Satori,"['python', 'azure', 'numpy', 'pandas', 'scikit...","{'cloud': ['azure'], 'libraries': ['numpy', 'p..."
771592,Data Engineer,Data Engineer,"Marousi, Greece",via Ai-Jobs.net,Full-time,False,Greece,2023-01-21 02:19:06,False,False,Greece,year,96773.0,NaN,Out There Media,"['sql', 'bigquery', 'spark', 'hadoop']","{'cloud': ['bigquery'], 'libraries': ['spark',..."

In [ ]:
gr_jobs.groupby('job_title_short')['salary_year_avg'].agg(['median','min','max','count']).sort_values(by='median', ascending=False)

                             median      min       max  count
job_title_short
Machine Learning Engineer  101029.0  72900.0  177283.0     14
Data Analyst                99500.0  53014.0  200000.0     16
Data Engineer               96773.0  45000.0  147500.0     24
Data Scientist              89885.0  51068.0  171121.0     12
Senior Data Scientist       89187.5  72900.0  200000.0      6
Software Engineer           81000.0  56700.0  156500.0      6
Business Analyst            63000.0  63000.0   72900.0      3
Senior Data Engineer        45000.0  45000.0   45000.0      1